// This file is a bridge to include the schemas generated by `build.rs`
// from `schema.hx`. Do not edit it manually.

pub mod generated_schemas {
    include!(concat!(env!("OUT_DIR"), "/generated_schemas.rs"));
}
